### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by seatsea** [Fiskie/gonav#1]
When trying to log the message "Login failed: Failed to fetch token, body: error=invalid_request" is returned.

App is running on a Oneplus One CM 13 (android 6.0.1).

**Comment by fiskWasTaken** [comment]
Interesting. Are you able to sign in to PTC via the official client? I've not seen this error before so I'm not sure where it came from.

**Comment by seatsea** [comment]
I was able to log in with official client and unless it's something else I did wrong, that seems to have fixed the problem.
